### ISSUE TITLE
Image extension changed after latest release

### ISSUE THREAD

**Issue by thomasjsn** [mahnunchik/gulp-responsive#113]
My `jpg` images got `jpeg` extensions after the latest release (2.13.0), is this intentional? All my images got new filenames because of this.

I'm not against this per se, and can adapt to these changes. But I'd like to know if it's likely to change back.

**Comment by Siilwyn** [comment]
Can confirm, I rolled back to `2.12.0`.

**Comment by sergeymorkovkin** [comment]
Confirm! Enexpected an annoying...

**Comment by pepelsbey** [comment]
Same here. I tried to use `extname: '.jpg'` parameter here and there, no luck.

**Comment by TheDancingCode** [comment]
I would revert the changes in #112. The multiple formats option isn't working and [this line](https://github.com/mahnunchik/gulp-responsive/blob/6100fdb196009166931da8a9bf98a5c823c8b320/lib/sharp.js#L196) that it introduced is now causing this issue.

**Comment by khalyomede** [comment]
Same here, I did this:

```javascript
const img = () =>
  src(["src/img/**/*.{png,jpg,jpeg,svg}", "!src/img/icon.png"])
    .pipe(plumber())
    .pipe(
      responsive({
        "**/*.*": [
          {
            width: 600,
            rename: {
              suffix: "-mobile"
            }
          },
          {
            width: 992,
            rename: {
              suffix: "-tablet"
            }
          },
          {
            width: 1200,
            rename: {
              suffix: "-laptop"
            }
          },
          {
            rename: {
              suffix: "-desktop"
            }
          }
        ]
      })
    )
    .pipe(imagemin())
    .pipe(dest("dist/img"))
    .pipe(webp())
    .pipe(dest("dist/img"))
    .pipe(browser.stream());
```

Even if I did not specified recipes for jpeg files specifically, the plugin did changed the extension, like it forced to output `.jpeg` instead of "keeping" the source extension.

**Comment by AddoSolutions** [comment]
Same issue, any hacky fixes yet? Tried `rename: f=>f.origin` to no avail

**Comment by StarpTech** [comment]
The PR https://github.com/mahnunchik/gulp-responsive/pull/129 fixed many issues. Please try and open another issue.
