### ISSUE TITLE
Upgrade to sharp@0.23.1

### ISSUE THREAD

**Issue by jeremyzilar** [mahnunchik/gulp-responsive#128]
I am running node `-v v12.11.1` and can currently use `sharp@0.23.1` with that version of node, but when I try to install gulp-responsive, it installs `sharp@0.21.3` as a dependency, which doesn't work with my version of node.

Is there a way I can use `sharp@0.23.1` with gulp-responsive?
Or is there a plan to upgrade?

https://www.npmjs.com/package/gulp-responsive

**Comment by StarpTech** [comment]
Fixed in https://github.com/mahnunchik/gulp-responsive/pull/129
