### ISSUE TITLE
Prevent processing unenlarged file without an error?

### ISSUE THREAD

**Issue by timrourke** [mahnunchik/gulp-responsive#17]
Hi there! Love this plugin.

I want to use `gulp-responsive` to batch-resize *all* images within a given directory to be resized down to several different sizes, for use with picturefill/srcset. I've noticed, however, that `gulp-responsive` will create new copies of a file with the same pixel dimensions if an option block defines a width target *higher* than the original source file.

How do I configure gulp-responsive to simply skip a config block if the original image is smaller than the destination output width of that config block?

I've set `withoutEnlargement` to `true` to at least prevent `gulp-responsive` from enlarging the images, but I hoped it would also cause the plugin to skip any images bigger than the config block.

Below, I've pasted my default config block.

```javascript
gulp.task('images', function() {
  browserSync.notify('Responsive images starting.');
  return gulp.src('images-source/**/*.{jpg,jpeg,png,tiff,webp,gif}')
    .pipe(newer('./html/images-build'))
    .pipe(plumber())
    .pipe(responsive({
      '**/*.{jpg,png,tiff,webp,gif}': [{
          width: 320,
          rename: {
            suffix: "-320"
          },
          withoutEnlargment: true,
          passThroughUnused: false
      },{
          width: 480,
          rename: {
            suffix: "-480"
          },
          withoutEnlargment: true,
          passThroughUnused: false
      },{
          width: 640,
          rename: {
            suffix: "-640"
          },
          withoutEnlargment: true,
          passThroughUnused: false
      },{
          width: 800,
          rename: {
            suffix: "-800"
          },
          withoutEnlargment: true,
          passThroughUnused: false
      },{
          width: 1024,
          rename: {
            suffix: "-1024"
          },
          withoutEnlargment: true,
          passThroughUnused: false
      },{
          width: 1280,
          rename: {
            suffix: "-1280"
          },
          withoutEnlargment: true,
          passThroughUnused: false
      },{
          width: 1600,
          rename: {
            suffix: "-1600"
          },
          withoutEnlargment: true,
          passThroughUnused: false
      },{
          width: 1890,
          rename: {
            suffix: "-1890"
          },
          withoutEnlargment: true,
          passThroughUnused: false
      },{
          width: 2400,
          rename: {
            suffix: "-2400"
          },
          withoutEnlargment: true,
          passThroughUnused: false
      },{
          rename: {
            suffix: "-original"
          },
          withoutEnlargment: true,
          passThroughUnused: false
      }]
    }))
    .pipe(gulp.dest('./html/images-build'));
});
```

Thanks!

**Comment by mahnunchik** [comment]
Hi @timrourke 

Sorry for the delay.

`skipOnEnlargement` option will be implemented in near future.

**Comment by mahnunchik** [comment]
Landed in 1.2.1

**Comment by mahnunchik** [comment]
Hi @timrourke 

Does `skipOnEnlargement` option solves your task?

**Comment by mahnunchik** [comment]
Hi @timrourke is issue resolved for you?

**Comment by edtalmadge** [comment]
I tried the skipOnEnlargement option, but it did not work as expected.
I'm using gulp-responsive v2.2.0

Instead of the image being skipped, an error is thrown.

I'm using this configuration.

`{
                // image-extralarge@2x.jpg is 2560 pixels wide
                width: 1280 * 2,
                skipOnEnlargement: true,
                rename: {
                    suffix: '-extralarge@2x',
                    extname: '.jpg',
                }`

The error I get is:

> events.js:154
      throw er; // Unhandled 'error' event
      ^
cted
  real width: 1000px, required width: 1280px
