### ISSUE TITLE
Errors if unsupported file type found

### ISSUE THREAD

**Issue by tbredin** [mahnunchik/gulp-responsive#2]
I usually have a bunch of svgs in my images directory which are processed by my image task - would be more robust if it simple skipped unsupported formats? Of course I can pipe/filter just the required file formats, but that seems less than ideal (for example I'm also piping svgs to gulp-imagemin)

``` events.js:72
        throw er; // Unhandled 'error' event
              ^
Error: Image does not match any config: imagename.svg
```

**Comment by AurelienDud** [comment]
Hello mahnunchik and thank you for your works ;)

Now, [Sharp API](http://sharp.dimens.io/en/stable/api/#input) say that :
> Buffer containing JPEG, PNG, WebP, GIF, SVG, TIFF or raw pixel image data

Do you think you could change the module to support SVG format ?

**Comment by mahnunchik** [comment]
Hi @AurelienDud 

`gulp-responsive` already supported everything that `sharp` understand. I've added test for SVG images.
