### ISSUE TITLE
Not working with subfolders

### ISSUE THREAD

**Issue by dandaka** [mahnunchik/gulp-responsive#28]
Expected behaviour:

1. gulp-responsive takes files from subfolders
1. transforms them
1. puts in subfolders in the output folder

Code:

```
gulp.task('responsive2', function () {
  gulp.src('./src/img/**/*.jpg')
    .pipe(print())
    .pipe(responsive([{
      name: 'banner.jpg',
      width: 600
      }],
      {
        errorOnUnusedImage: false
      }
    ))
    .pipe(gulp.dest('./public/img/'));
});
```

Log:

```
[frontend-boilerplate] gulp responsive2                               master  ✭
[15:31:46] Using gulpfile ~/projects/frontend-boilerplate/gulpfile.js
[15:31:46] Starting 'responsive2'...
[15:31:46] Finished 'responsive2' after 9.45 ms
[15:31:46] src/img/imgs/banner.jpg

stream.js:75
      throw er; // Unhandled stream error in pipe.
      ^
Error: Available images do not match following config:
  - `banner.jpg`
```

**Comment by dandaka** [comment]
Hi, any news on this? Maybe you could direct me to find the fix somewhere?

**Comment by mahnunchik** [comment]
Hi @dandaka could you please reproduce the error with `gulp-responsive@2.0.0`. It should log the filename.

**Comment by dandaka** [comment]
I think I get idea, why it doesn't work. I got this code working:

```
// Test subfolders
gulp.task('responsive-subfolders', function () {
  gulp.src(['./src/content/portfolio/**/*.png'])
  .pipe(print())
  .pipe(responsive({
      '**/*.png': [
        {
          width: 2000,
          rename: rename2000,
          quality: 80
        }]},
    {
      errorOnUnusedImage: false,
      errorOnEnlargement: false
    }))
  .pipe(gulp.dest('./tmp/'));
});
```

The difference is in this line:
```'**/*.png': [``` — no error
```'*.png': [``` — Error: Available images do not match following config:

Is it a bug? Since in your example you don't specify folders (only filenames), expected behaviour here is the same — no ```**/```, only file ```*.png```.

**Comment by DOMUSNETWORK** [comment]
Hey @mahnunchik I'm using gulp-responsive@2.0.0 and I've managed to get the same error when using 'gulp-newer', any ideas?
``` javascript
    function responsiveFn() {
        return gulp.src(paths.source + '/images/original/**/*.{jpg,png,gif}')
            .pipe(newer(paths.source + '/images/responsive'))
            .pipe(load.responsive(conf.responsive, {
                errorOnUnusedConfig: false,
                errorOnUnusedImage: false,
                passThroughUnused: true,
                quality: 70,
                compressionLevel: 6,
                progressive: true,
                withMetadata: false
            }))
            .pipe(gulp.dest(paths.source + '/images/responsive'));
        }
```

log:
`[10:23:53] gulp-responsive: Available images do not match the following config:
  - `**/*.jpg`
  - `**/*.jpg`
  - `**/*.jpg`
  - `**/*.png`
  - `**/*.png`
[10:23:53] Finished 'responsive-images' after 33 ms`

**Comment by mahnunchik** [comment]
Hi @dandaka 

It is exactly how [`minimatch`](https://github.com/mahnunchik/gulp-responsive/blob/master/lib/index.js#L40) works.

[minimatch](https://github.com/isaacs/minimatch) is used by `gulp` itself. So I decided to use the same matching library for my plugin.

match any file and any subfolder
```js
gulp.src(['./src/content/portfolio/**/*.png'])
  .pipe(responsive({
      '**/*.png': [{...}]
    }))
```

match any file
```js
gulp.src(['./src/content/portfolio/*.png'])
  .pipe(responsive({
      '*.png': [{...}]
    }))
```

match any file
```js
gulp.src(['./src/content/portfolio/*.png'])
  .pipe(responsive({
      '**/*.png': [{...}]
    }))
```

not match
```js
gulp.src(['./src/content/portfolio/**/*.png'])
  .pipe(responsive({
      '*.png': [{...}]
    }))
```

**Comment by dandaka** [comment]
Thank you for clarification. Still think it is strange behaviour.
