### ISSUE TITLE
Select format output per image

### ISSUE THREAD

**Issue by dandaka** [mahnunchik/gulp-responsive#29]
Do I understand correctly, that right now it is impossible to force output format? Say, take 10 PNG images and convert them to JPG?

Sharp has this feature
http://sharp.dimens.io/en/stable/api/#toformatformat

I have tried `toFormat` in config JSON with no result

```
  gulp.src('./src/img/05OC/*.png')
    .pipe(print())
    .pipe(responsive([{
      name: '*.png',
      width: 600,
      toFormat: 'jpeg'
    }],
    {
      errorOnUnusedImage: false
    }
    ))
    .pipe(gulp.dest('./public/img/'));
});
```

**Comment by mahnunchik** [comment]
Hi @dandaka 

It already works in `next` branch https://github.com/mahnunchik/gulp-responsive/tree/next

See `format` option: https://github.com/mahnunchik/gulp-responsive/blob/next/lib/config.js#L88

But it isn't documented and tested yet =(

**Comment by dandaka** [comment]
Works for me, thank you!
