### ISSUE TITLE
Rename extension according to output format

### ISSUE THREAD

**Issue by dandaka** [mahnunchik/gulp-responsive#30]
### Right now ###

1. Take folder of PNG files
2. Convert them to JPG files
3. Names are preserved (*.png)

### Should be ###

1. Additional option "extensionMatchOutput", defaults: true
2. When true, output files extension are named according to output format

**Comment by mahnunchik** [comment]
Hi @dandaka 

Could you please show your config.

**Comment by dandaka** [comment]
1. This is what I got to make it work (should be)
https://github.com/dandaka/frontend-boilerplate/blob/master/gulpfile.js#L82-L95

2. This was working as explained in `right now`
https://github.com/dandaka/frontend-boilerplate/blob/ec641db2e2f43b5109f4a197375a932062e43d4e/gulpfile.js#L82-L94

**Comment by mahnunchik** [comment]
1. You can omit `format` option here: https://github.com/dandaka/frontend-boilerplate/blob/master/gulpfile.js#L87
Format will be parsed from output filename as it is renamed to `.jpg`

2. You are able to specify `format` option and for example custom extname:

```js
gulp.task('responsive', function () {
  gulp.src('./src/img/05OC/*.png')
    .pipe(responsive([{
      name: '*.png',
      width: 600,
      format: 'jpeg',
      rename: { extname: '.my-custom-jpg' }
    }],
    {
      errorOnUnusedImage: false
    }
    ))
    .pipe(gulp.dest('./public/img/'));
});
```

**Comment by dandaka** [comment]
Ok, updated the docs
https://github.com/dandaka/gulp-responsive/commit/ee6916f5a4b02ab360f7ab56eb765931e1fd9fe5
