### ISSUE TITLE
Error: File 'myImage.png': VipsOperation: class "webpsave_buffer" not found

### ISSUE THREAD

**Issue by edtalmadge** [mahnunchik/gulp-responsive#36]
When I try to create webp images, I get the following error message:
Error: File 'myImage.png': VipsOperation: class "webpsave_buffer" not found

I am able to create jpg and png images successfully.

I'm on:
Windows 10
Node v5.9.1

Here's the configuration I'm using:

```
{
  width: 200,
  rename: {
    suffix: '-small',
    extname: '.webp'
  }
}
```

**Comment by mahnunchik** [comment]
Hi @edtalmadge 

Sorry but:
> The WebP format is currently unavailable on Windows.

http://sharp.dimens.io/en/stable/install/#windows

@lovell do you have any plans for this feature?

**Comment by lovell** [comment]
A cross-compiled libwebp v0.4.3 for Windows [fails](https://github.com/jcupitt/build-win32/issues/11#issuecomment-148220052) but the new-ish v0.5.0 release *should* be OK. Once the groundwork laid by https://github.com/jcupitt/build-win64/pull/4 (or similar) is available I'll attempt to introduce it.

**Comment by mahnunchik** [comment]
@lovell Thank you for clarification.

**Comment by edtalmadge** [comment]
Ok, sounds good, thanks.

**Comment by lovell** [comment]
v0.5.0 of libwebp appears to be stable when cross-compiling so sharp v0.15.0 will add support for the WebP format on Windows. Subscribe to https://github.com/lovell/sharp/issues/369 for updates.

**Comment by mahnunchik** [comment]
Thank you for update!
