### ISSUE TITLE
PNG are twice bigger than with imageMagick

### ISSUE THREAD

**Issue by bokanist** [mahnunchik/gulp-responsive#40]
The PNG output of gulp-responsive are twice bigger than what I get from grunt-responsive (which is using imageMagick).

152x174 image > 3.5KB with imageMagick, 7KB with gulp responsive

With these settings it's a little bit better at 6.7KB
progressive: true,
compressionLevel: 9,
errorOnUnusedConfig: false,
errorOnUnusedImage: false,
errorOnEnlargement: false

**Comment by mahnunchik** [comment]
Duplicate #34
