### ISSUE TITLE
background-*.jpg is not working

### ISSUE THREAD

**Issue by slavikse** [mahnunchik/gulp-responsive#43]
If no pictures the mask background-*.jpg or *, the task results in an error.
the task must be turned off manually until it is needed and should include when the pictures appear.

Error: 
```
Message:
    Available images do not match the following config:
  - `background-*.jpg`
  - `background-*.jpg`
  - `background-*.jpg`
Details:
    domainEmitter: [object Object]
    domain: [object Object]
    domainThrown: false
```
Please add the correct handling of such situations without completing the task fail.
Thank you! :)

**Comment by slavikse** [comment]
close please.
a solution was found in the configs: errorOnUnusedConfig

**Comment by mahnunchik** [comment]
Hi @slavikse thanks 😉
