### ISSUE TITLE
Crop

### ISSUE THREAD

**Issue by plonko** [mahnunchik/gulp-responsive#45]
How does one use the crop option?

thnx

**Comment by Astorsoft** [comment]
Hi, I'm having the same question, according to your doc you could think that you just have to give true, but it is expecting a sharp strategy according to sharp's doc, something along the lines of sharp.strategy.entropy

**Comment by ericmasiello** [comment]
Same issue/question here

**Comment by TheDancingCode** [comment]
Info can be found [here](http://sharp.dimens.io/en/stable/api-resize/#crop).

You can pass a gravity point to crop to an edge or corner, choosing among `north`, `northeast`, `east`, `southeast`, `south`, `southwest`, `west`, `northwest`, `center` and `centre`.
Or you can pass a strategy to crop dynamically, choosing between `entropy` and `attention`.

You pass your choice as a string:
```js
{
  '*.png': {
    width: 400,
    height: 200,
    crop: 'northeast'
  }
}
```
