### ISSUE TITLE
doubling the width of the unknown

### ISSUE THREAD

**Issue by slavikse** [mahnunchik/gulp-responsive#53]
a double width if it is unknown?
200% - does not work
2 * 100% - does not work

**Comment by mahnunchik** [comment]
Hi @slavikse 

Could you please test it again. Working configuration should be like:
```js
.pipe($.responsive({
  '**/*.png': [{
    width: '200%',
    withoutEnlargement: false
  }]
})
```

**Comment by slavikse** [comment]
Hi @mahnunchik. Thank you! :-)
