### ISSUE TITLE
Allow kernel options.

### ISSUE THREAD

**Issue by jdalton** [mahnunchik/gulp-responsive#54]
I noticed this plugin forwards interpolation to [sharp interpolator](http://sharp.dimens.io/en/stable/api/#interpolatewithinterpolator) to configure how enlarging images is handled but doesn't forward kernel to configure how reducing images is handled.

**Comment by jdalton** [comment]
Thank you!

**Comment by mahnunchik** [comment]
Hi @jdalton 

`kernel` option is landed in version 2.6.0 https://www.npmjs.com/package/gulp-responsive

Thank you! 😉
