### ISSUE TITLE
update sharp v0.17

### ISSUE THREAD

**Issue by slavikse** [mahnunchik/gulp-responsive#61]
previous settings issue:
```
vips warning: VipsJpeg: error reading resolution
(node:22753) DeprecationWarning: quality: use jpeg({ quality: ... }), webp({ quality: ... }) and/or tiff({ quality: ... }) instead
(node:22753) DeprecationWarning: progressive: use jpeg({ progressive: ... }) and/or png({ progressive: ... }) instead
(node:22753) DeprecationWarning: withoutChromaSubsampling: use jpeg({ chromaSubsampling: "4:4:4" }) instead
vips warning: VipsJpeg: error reading resolution
(node:22753) DeprecationWarning: compressionLevel: use png({ compressionLevel: ... }) instead
vips warning: VipsJpeg: error reading resolution
```
I tried to correct the settings on the:
```
param.jpeg = {progressive: true};
param.png = {progressive: true};
```
warnings remained.
how to fix?

**Comment by mahnunchik** [comment]
Hi @slavikse 

I've faced with the same issue: https://github.com/lovell/sharp/issues/657

Will fix asap.

**Comment by slavikse** [comment]
@mahnunchik  this error is understandable.
I will wait. Thank you :)

**Comment by mahnunchik** [comment]
Hi @slavikse 

Warnings like:
```
vips warning: VipsJpeg: error reading resolution
```
can be ignored, more info here https://github.com/lovell/sharp/issues/657

DeprecationWarning I will fix in the next major release.

**Comment by slavikse** [comment]
Hi @mahnunchik
Thank you!
Cool utility do! :)

**Comment by strarsis** [comment]
Will this be fixed in near future?

**Comment by developer239** [comment]
I can still see the errors :)

**Comment by michaeljota** [comment]
Can be `sharp` made `peerDependecy`? This way we wouldn't have to wait for this to update sharp, and can use the latest version. If you are worried about compatibility errors, you could use version range, but even then, we could use test with the latest to see if that works.

**Comment by marcospgp** [comment]
Bump!
