### ISSUE TITLE
Resize based on image orientation.

### ISSUE THREAD

**Issue by patrickcate** [mahnunchik/gulp-responsive#8]
It would be cool to have an option to resize images at different sizes based on whether they are portrait or landscape oriented images. I didn't seem an option for this so I assume it isn't currently possible.

**Comment by JosefJezek** [comment]
:+1:

**Comment by mahnunchik** [comment]
Hi @patrickcate @JosefJezek 

Could you please clarify what you mean.

For example, suppose we have two images:
* 500 x 200 - landscape oriented
* 200 x 500 - portrait oriented

**Comment by patrickcate** [comment]
If I have a landscape image 500 x 200, I may want to resize it to a certain width (say 100px wide). A 200 x 500 portrait image to 100px wide would be much larger however due to the increase height. It would be nice to resize these portrait images at a different width, or resize to a height measurement. 

Right now my use case is I have a lot of website photos which contain both portrait and landscape photos. When batch resizing them at different widths the landscape photos are fine, but the portrait ones are too large at the same width. Being able to resize the portrait ones to a different width or height would easily solve the issue. I could manually separate the two orientations and resize them differently in separate tasks, but this isn't a smooth workflow to maintain. Being able to set different resizes based on the photos orientation would be solve this perfectly.

**Comment by mahnunchik** [comment]
I think it has already been implemented in release https://github.com/mahnunchik/gulp-responsive/releases/tag/1.0.7

 `max` option allows you to do what you describe :wink: 

More info here: https://github.com/lovell/sharp#max

Is that what you wanted?

**Comment by patrickcate** [comment]
The max size option works if you want to resize a portrait image differently by height, but unfortunately not if you want to resize by another width.

**Comment by mahnunchik** [comment]
Hi @patrickcate 

Current behavior of `max` option.

For example we have two files:
* file A - 500 x 200 pixels
* file B - 200 x 500 pixels

Config:
```javascript
{
  width: 100,
  height: 100,
  max: true
}
```

File A will be resized to 100 x 40
File B will be resized to 40 x 100

Is it what you want? Or not?

**Comment by mahnunchik** [comment]
Please reopen if necessary.
